# Generated by Django 3.2 on 2021-10-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
