# Generated by Django 3.2 on 2021-10-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
