# Generated by Django 3.2 on 2021-10-21 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_seat_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.section'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='rank',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.rank'),
        ),
    ]
